[package]
name = "timeturner"
version = "0.1.0"
authors = ["Stephen Duncan <jrduncans@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
chrono = "0.4"
chrono-tz = "0.5"
