name: CI
on:
  pull_request:
  push:
    paths-ignore:
    - '.github/workflows/release.yaml'
    - 'README.md'
    branches:
    - main
env:
  CARGO_TERM_COLOR: always
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        override: true
        profile: minimal
        toolchain: stable

    - name: Set Timezone
      uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "America/Los_Angeles"
    
    - name: Test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        override: true
        profile: minimal
        components: rustfmt, clippy
        toolchain: stable

    - name: Check Format
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check

    - name: Check Clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --all-targets --all-features -- -D warnings -D clippy::pedantic
