name: Release
on:
  pull_request:
  push:
    branches:
    - main
env:
  CARGO_TERM_COLOR: always
jobs:
  release:
    name: Release
    strategy:
      matrix:
        job:
          - {os: ubuntu-latest, target: x86_64-unknown-linux-musl}
          - {os: macos-latest, target: x86_64-apple-darwin}
          - {os: macos-latest, target: aarch64-apple-darwin}

    runs-on: ${{ matrix.job.os }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        override: true
        profile: minimal
        toolchain: stable
        target: ${{ matrix.job.target }}
    
    - name: Build Release
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --verbose --release --target ${{ matrix.job.target }}

    - name: Strip release binary (linux and macos)
      if: matrix.job.os == 'ubuntu-latest' || matrix.job.os == 'macos-latest'
      run: strip "target/${{ matrix.job.target }}/release/timeturner"
